language: generic

env:
  matrix:
    - EMACS=emacs25

install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get update -qq &&
  sudo apt-get -qq -f install &&
  sudo apt-get install -qq $EMACS ${EMACS}-el;

script:
  $EMACS --batch --no-init-file --load reveal-init.el --find-file vortrag.org --funcall org-reveal-export-to-html

notifications:
  email: false
